In [1]:
import numpy as np
import tensorflow as tf

In [2]:
print(tf.__version__)

2.0.0-beta0


## Tensors & Operations

In [3]:
# constant
print(tf.constant(3))

tf.Tensor(3, shape=(), dtype=int32)


In [4]:
# tf.Tensorを生成する演算
print(tf.add(1, 2))
print(tf.add([1, 2], [3, 4]))
print(tf.square(5))
print(tf.reduce_sum([1, 2, 3, 4]))

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)


In [5]:
# 行列、shape, dtype
x = tf.matmul([[1, 2], [0, 1]], [[1], [1]])
print(x)
print(x.shape)
print(x.dtype)

tf.Tensor(
[[3]
 [1]], shape=(2, 1), dtype=int32)
(2, 1)
<dtype: 'int32'>


### NumPyとの関係

In [6]:
ndarray = np.ones(shape=[2, 2])
print(ndarray)

# tensorflowの演算によるtf.Tensorへの自動変換
tensor = tf.multiply(ndarray, 3)
print(tensor)

# numpy演算によるnumpy配列への自動変換
print(np.dot(tensor, [1, 2]))

# numpy配列への変換
print(tensor.numpy())

[[1. 1.]
 [1. 1.]]
tf.Tensor(
[[3. 3.]
 [3. 3.]], shape=(2, 2), dtype=float64)
[9. 9.]
[[3. 3.]
 [3. 3.]]


## Variables

[カスタムトレーニングの項](https://www.tensorflow.org/beta/tutorials/eager/custom_training)によると、

- Tensor: immutable stateless objects
- Variable: mutable stateful objects

デフォルトでVariableはtf.GradientTapeにwatchされる

In [7]:
v = tf.Variable(1.0)
print(v)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.0>


In [8]:
v.assign(2.0)
print(v)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=2.0>


In [9]:
v.assign(tf.square(v))
print(v)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=4.0>


In [10]:
v.assign_add(1.2)
print(v)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=5.2>
