In [1]:
import torch

print(torch.__version__)

1.1.0


## Automatic Differentiation

In [2]:
x = torch.ones(2, 3)

print(x)
print(x.requires_grad)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
False


In [3]:
x = torch.ones(2, 3, requires_grad=True)
y = x * x
z = y.sum()

z.backward()

print(y)
print(x.grad)

tensor([[1., 1., 1.],
        [1., 1., 1.]], grad_fn=<MulBackward0>)
tensor([[2., 2., 2.],
        [2., 2., 2.]])


In [4]:
x = torch.ones(2, 3, requires_grad=True)
y = x * x

y.backward(torch.tensor([[0.0, 1.0, 2.0], [3.0, 4.0, 5.0]]))

print(y)
print(x.grad)

tensor([[1., 1., 1.],
        [1., 1., 1.]], grad_fn=<MulBackward0>)
tensor([[ 0.,  2.,  4.],
        [ 6.,  8., 10.]])


### Higher order gradients

In [5]:
x = torch.ones(1, requires_grad=True)
y = x * x * x
z = y.sum()

dz_dx, = torch.autograd.grad(z, x, create_graph=True)

dz_dx.backward()
x.grad

tensor([6.])

$$
\begin{equation}
x = 
\begin{pmatrix}
x_{11} && x_{21} \\
x_{12} && x_{22}
\end{pmatrix}
, \\
y = \sum_{i, j} x_{ij}^3, \\
z = y + \sum_{i, j} \frac{\partial y}{\partial x_{ij}}
\end{equation}
$$

において
$$
\frac{\partial z}{\partial x_{ij}} = 3x_{ij}^2 + 6x_{ij}
$$
を計算する

In [6]:
x = torch.tensor([[1.0, 2.0], [-5.0, -1.0]], requires_grad=True)
y = (x**3).sum()

dy_dx, = torch.autograd.grad(y, x, create_graph=True)
z = y + dy_dx.sum()

z.backward()
print("grad by torch autograd:")
print(x.grad)

x_numpy = x.detach().numpy()
print("correct grad:")
print(3 * x_numpy**2 + 6 * x_numpy)

grad by torch autograd:
tensor([[ 9., 24.],
        [45., -3.]])
correct grad:
[[ 9. 24.]
 [45. -3.]]
