In [1]:
import torch

print(torch.__version__)

1.1.0


## Automatic Differentiation

In [2]:
x = torch.ones(2, 3)

print(x)
print(x.requires_grad)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
False


In [3]:
x = torch.ones(2, 3, requires_grad=True)
y = x * x
z = y.sum()

z.backward()

print(y)
print(x.grad)

tensor([[1., 1., 1.],
        [1., 1., 1.]], grad_fn=<MulBackward0>)
tensor([[2., 2., 2.],
        [2., 2., 2.]])


In [4]:
x = torch.ones(2, 3, requires_grad=True)
y = x * x

y.backward(torch.tensor([[0.0, 1.0, 2.0], [3.0, 4.0, 5.0]]))

print(y)
print(x.grad)

tensor([[1., 1., 1.],
        [1., 1., 1.]], grad_fn=<MulBackward0>)
tensor([[ 0.,  2.,  4.],
        [ 6.,  8., 10.]])


### Higher order gradients

In [5]:
x = torch.ones(1, requires_grad=True)
y = x * x * x
z = y.sum()

dz_dx, = torch.autograd.grad(z, x, create_graph=True)

dz_dx.backward()
x.grad

tensor([6.])